import { createTheme, createThemeContract } from '@vanilla-extract/css';

const colors = {
  primary: '',
  // surfaceTint: '',
  // onPrimary: '',
  // primaryContainer: '',
  // onPrimaryContainer: '',
  // secondary: '',
  // onSecondary: '',
  // secondaryContainer: '',
  // onSecondaryContainer: '',
  // tertiary: '',
  // onTertiary: '',
  // tertiaryContainer: '',
  // onTertiaryContainer: '',
  // error: '',
  // onError: '',
  // errorContainer: '',
  // onErrorContainer: '',
  // background: '',
  // onBackground: '',
  // surface: '',
  // onSurface: '',
  // surfaceVariant: '',
  // onSurfaceVariant: '',
  // outline: '',
  // outlineVariant: '',
  // shadow: '',
  // scrim: '',
  // inverseSurface: '',
  // inverseOnSurface: '',
  // inversePrimary: '',
  // primaryFixed: '',
  // onPrimaryFixed: '',
  // primaryFixedDim: '',
  // onPrimaryFixedVariant: '',
  // secondaryFixed: '',
  // onSecondaryFixed: '',
  // secondaryFixedDim: '',
  // onSecondaryFixedVariant: '',
  // tertiaryFixed: '',
  // onTertiaryFixed: '',
  // tertiaryFixedDim: '',
  // onTertiaryFixedVariant: '',
  // surfaceDim: '',
  // surfaceBright: '',
  // surfaceContainerLowest: '',
  // surfaceContainerLow: '',
  // surfaceContainer: '',
  // surfaceContainerHigh: '',
  // surfaceContainerHighest: '',
};

export const vars = createThemeContract({
  colors: {
    primary: '',
    secondary: '',
    tertiary: '',
  },
});

export const testThemeClass = createTheme(vars, {
  colors: {
    primary: '#00687b',
    secondary: '#123456',
    tertiary: '#000000',
  },
});
